# Generated by Django 6.0.5 on 2026-09-27 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sprint1_academic_management'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecorridoTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40, unique=True)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'recorrido_transporte',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='inscripto_comedor',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AuditoriaCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('entidad', models.CharField(max_length=80)),
                ('registro_id', models.CharField(max_length=80)),
                ('accion', models.CharField(max_length=30)),
                ('campos', models.JSONField(default=list)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_auditados', to='core.usuario')),
            ],
            options={
                'db_table': 'auditoria_cambio',
                'ordering': ['-fecha', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='GrupoDeportivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(max_length=30)),
                ('dia_semana', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=12)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos', to='core.disciplinadeportiva')),
                ('profesor_responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_deportivos', to='core.docente')),
            ],
            options={
                'db_table': 'grupo_deportivo',
                'ordering': ['disciplina__nombre', 'nivel', 'dia_semana', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='InscripcionDeportiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Finalizada', 'Finalizada')], default='Activa', max_length=20)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones_deportivas', to='core.alumno')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='core.grupodeportivo')),
            ],
            options={
                'db_table': 'inscripcion_deportiva',
            },
        ),
        migrations.CreateModel(
            name='InscripcionTransporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('Activa', 'Activa'), ('Finalizada', 'Finalizada')], default='Activa', max_length=20)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones_transporte', to='core.alumno')),
                ('recorrido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones', to='core.recorridotransporte')),
            ],
            options={
                'db_table': 'inscripcion_transporte',
            },
        ),
        migrations.AddConstraint(
            model_name='grupodeportivo',
            constraint=models.UniqueConstraint(fields=('disciplina', 'nivel', 'dia_semana', 'hora_inicio', 'hora_fin'), name='uniq_grupo_deportivo_horario'),
        ),
        migrations.AddConstraint(
            model_name='inscripciondeportiva',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'Activa')), fields=('alumno', 'grupo'), name='uniq_inscripcion_deportiva_activa'),
        ),
        migrations.AddConstraint(
            model_name='inscripciontransporte',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'Activa')), fields=('alumno',), name='uniq_transporte_activo_por_alumno'),
        ),
    ]
